### ISSUE TITLE
Please add a example usage

### ISSUE THREAD

**Issue by restuwahyu13** [winstonjs/winston-transport#139]
Please add a example usage about this library to create a simple custom transport, because the documentation is not clean, this is my code and it's not working, can anyone help me ?. Thank you

```ts
import Transport from 'winston-transport'

export class CustomTransport extends Transport {
  constructor() {
    super()
  }

  log(info, callback) {
    setImmediate(() => {
      this.emit('logged', info)
    })

    this.silent = true
    this.write(JSON.stringify({ message: info.message }))
    callback()
  }
}
```

**Comment by wbt** [comment]
You may want to try asking usage questions on StackOverflow or, with a question as nebulous as this ('not working' isn't a clear example of exactly what you expect and what different behavior you observe) perhaps just [browse existing questions there](https://stackoverflow.com/search?q=winston-transport).  You can also try [GitHub Code Search](https://github.com/features/code-search/signup) if you're in the beta or get on the list if not.
