### ISSUE TITLE
Version 3.3.0 breaks transports for winston (TransportStream cannot be invoked without 'new')

### ISSUE THREAD

**Issue by dannypaz** [winstonjs/winston-transport#22]
Winston: 3.0.0-rc5
Winston Transport: 3.3.0

I receive ```TypeError: Class constructor TransportStream cannot be invoked without 'new'
    at new module.exports (../node_modules/winston/lib/winston/transports/file.js:32:19)``` after npm installing and I think its due to the recent 3.3.0 changes that were pushed.

package-lock.json
```
    "winston-transport": {
      "version": "3.3.0",
      ...
    },
```

**Application Code:**
```
...
const winston = require('winston')

const logger = winston.createLogger({
  level: (process.env.NODE_ENV === 'production') ? 'info' : 'debug',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.json()
  ),
  json: true,
  humanReadableUnhandledException: true,
  handleExceptions: true,
  transports: [
    new winston.transports.File({ filename: 'error.log', level: 'error' }),
    new winston.transports.File({ filename: 'combined.log' })
  ]
})

if (process.env.NODE_ENV !== 'production') {
  logger.add(new winston.transports.Console({
    format: winston.format.combine(
      winston.format.timestamp(),
      winston.format.simple()
    )
  }))
}
```

Reverting to 3.2.1 resolves the issue. I wanted to report this issue, but can help if needed in the morning (PST)

**Comment by ChrisAlderson** [comment]
Can confirm, the easiest solution is to update winston to version `>= 3.0.0-rc2`

**Comment by indexzero** [comment]
D'oh. I forgot that there that breaking change in the ES6 migration. It's been less than 24 hours so I can unpublish and re-release as `4.0.0`

**Comment by indexzero** [comment]
Version has been unpublished. May take an hour or so for the `npm` registry caches to clear. You will also need to regenerate any lockfiles. Sorry for the confusion.

**Comment by indexzero** [comment]
Thanks for reporting this so quickly @dannypaz – glad we were able to catch it in the 24 hour unpublish time window `npm` gives. 

- `4.0.0` is now released with this breaking change. 
- `3.3.0` has been removed permanently and the incident has been documented in `CHANGELOG.md`

**Comment by indexzero** [comment]
@dannypaz can you try running against `master` for `winston` and confirm this no longer repros? I don't want to put out `winston@3.0.0-rc6` without confirming this is really fixed – mainly b/c I don't understand the issue itself:

- Your code uses `new`
- Nothing in `winston` itself uses the implicit `new` that was removed in `winston-transport@4.0.0`.

... please let us know 🙏

**Comment by dannypaz** [comment]
@indexzero looks good to me. winston@3.0.0-rc5 resolves to winston-transport@3.2.1 and I receive no errors. 

Thanks for the quick response on this.

**Comment by dannypaz** [comment]
@indexzero I read through the changelog. if TransportStream requires the use of `new` then https://github.com/winstonjs/winston/blob/3.0.0-rc5/lib/winston/transports/file.js#L32 and a few other areas would fail?

**Comment by indexzero** [comment]
@dannypaz sorry if I wasn't clear – can you try `master`? e.g. put this in your package.json:

``` json
"winston": "winstonjs/winston#master"
```

**Comment by indexzero** [comment]
@dannypaz to be clear: on `master` those things have been changed to ES6 `class` as well so there would be no such incompatibility.
