### ISSUE TITLE
Release latest version with handleRejections property

### ISSUE THREAD

**Issue by betalb** [winstonjs/winston-transport#47]
Release latest version with handleRejections property

Otherwise setting `handleRejections` property in options, during transport creation won't work

```const { createLogger, transports } = require('winston');
const assert = require('assert');

const transport = new transports.Console({
  handleExceptions: true,
  handleRejections: true,
});

assert(transport.handleExceptions === true); // Works
assert(transport.handleRejections === true); // Fails
```

**Comment by PeterBurner** [comment]
is there any reason why this hasn't been released yet??

**Comment by sevetseh28** [comment]
I also saw handleRejections cannot be set with the latest release but it's already documented the README.

**Comment by betalb** [comment]
I see that fix is released
