### ISSUE TITLE
Undefined is a legacy winston transport.

### ISSUE THREAD

**Issue by Alexis01** [winstonjs/winston-transport#51]
Hi,

Im wrinting my own winston transport.

```
const Transport = require('winston-transport');

class KafkaLoggerTransport extends Transport  .....

```

And when I create it i go the next error   "undefined is a legacy winston transport. Consider upgrading: "
```
new Logger({
      transports: [new KafkaLoggerTransport() ],
      exitOnError: false
    })
```
Any ideas?

Thanks

**Comment by rodrigo-rufino** [comment]
Did you find out what this was happening?

**Comment by Alexis01** [comment]
@rodrigo-rufino I always get the message and i dont investigate more. I think that this repo is not being manteined.

**Comment by jwhitmarsh** [comment]
For anyone coming to this in 2020, this happens if you define you `log` handler as anything other than `log(info, callback)` (the old way was `log(level, message, meta, callback)`
