### ISSUE TITLE
Inconsistent index.d.ts in the published version 4.4.0

### ISSUE THREAD

**Issue by ormauda** [winstonjs/winston-transport#66]
Hi,

In the latest published version, 4.4.0, the namespace TransportStream in the index.d.ts doesn't contain the field 'handleRejections', although it appears in index.js.
The field exists in the index.d.ts in the master branch, but the library wasn't published since this update.

Hence, Typescript users can't use this field, even though it is documented in the winston library.
Therefore the action needed here is to publish the library with this fix.

Thanks.

**Comment by ryancraigmartin** [comment]
Also currently facing this issue.

**Comment by mitsos1os** [comment]
Same here!

**Comment by imyourmanzi** [comment]
Yes, same here.  The PR for this was already merged (#44) just waiting on a release!

**Comment by mateuscelio** [comment]
The release stills inconsistent with master branch

**Comment by wbt** [comment]
4.4.1 was just released; hopefully that fixes it!
