### ISSUE TITLE
Feature Request: Missing `name: string` in TransportStream Type [PR Added! :) ]

### ISSUE THREAD

**Issue by Swivelgames** [winstonjs/winston-transport#69]
The TransportStream Type is currently lacking the `name` property.

While this might not be utilized specifically by `winston` itself, it is very useful and has been utilized by other modules that extend `winston`. This is utilized by things like `winston-cloudwatch`. It would be very helpful to add it, at least to the `TransportStream` type as an optional property. This would enable people to use `name` if they want to.

I've produced PR #68 if you all would like to release it along with Issue #66 which is also currently unreleased.

**Comment by Swivelgames** [comment]
For anyone else running into this issue, my current solution for this in my own implementation is a little messy, but it works:

```typescript
declare class NamedTransportStream extends winstonTransport {
    public name?: string;
}

export const transport = (logger.transports as NamedTransportStream[]).find(
    ({ name }) => name === TRANSPORT_NAME
);
```

Obviously, another solution for this would be to do the following:

```typescript
const transport = new winstonCloudwatch({
  name: TRANSPORT_NAME,
  logGroupName: WINSTON_LOG_GROUP,
  logStreamName: WINSTON_STREAM_NAME,
  cloudWatchLogs: new aws.CloudWatchLogs(),
} as winstonCloudwatch.CloudwatchTransportOptions),

const logger = winston.createLogger({
    level: 'info',
    format: winston.format.json(),
    defaultMeta: {
        service: 'user-service',
    },
    transports: [
        new winston.transports.Console({ format: winston.format.json() }),
        transport,
    ],
});
```

Then you can reference it later. That being said, it's not as elegant as instantiating all of your transports inline. But it's a notable solution if you need direct access to the transport. For instance, in the case of `kthxbye()` in `winston-cloudwatch`.

Iterating is doable, but TypeScript doesn't like it simply because of the lack of the `name` property.

Another potential solution is using `.find(transport => transport instanceof winstonCloudwatch)`, but it's slower than doing a simple comparison for the `name` property.

The only time when defining your transport outside of the `createLogger` statement wouldn't be viable is if you're trying to snag access a transport outside of the area in which you're defining your `winston` logger and don't have the ability to make your transport an additional export. That, or if you're trying to access particular transports in some sort of wrapper class, in which case `name` is probably the most intuitive.

**Comment by Swivelgames** [comment]
Is this repo still active?

**Comment by wbt** [comment]
Not as active as it really should be, but a few more of us part-part-time volunteers have been added since the PR.
